[general]
platform = "Windows"
unique_id = 0
sessionid = 0
ttl-tar-id = 0

[tts]
enabled = true
model = 0
volume = 0.5
voice_variation = 1.0
speaking_variation = 1.0
speed = 2.0
normalize_audio = false
